/*
Provider is the main building block of riverpod
It acts like an central place that we can define and encapsulate state and then provide access to that state to multiple widgets
 */

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:shopping_cart/models/product.dart';

part 'products_provider.g.dart'; // this is the file which riverpod will generate

const List<Product> allProducts = [
  Product(id: '1', title: 'Ear Buds', price: 343, image: 'assets/products/earbuds.png'),
  Product(id: '2', title: 'Headphones', price: 78, image: 'assets/products/headphones.png'),
  Product(id: '3', title: 'Yellow Hoodie', price: 189, image: 'assets/products/hoodie.png'),
  Product(id: '4', title: 'Denim Jeans', price: 32, image: 'assets/products/jeans.png'),
  Product(id: '5', title: 'Smartwatch', price: 134, image: 'assets/products/smartwatch.png'),
  Product(id: '6', title: 'Sneakers', price: 81, image: 'assets/products/sneakers.png'),
  Product(id: '7', title: 'Wrist watch', price: 45, image: 'assets/products/watch.png'),
  Product(id: '8', title: 'Water Bottle', price: 23, image: 'assets/products/waterbottle.png'),
  Product(id: '9', title: 'Red Backpack', price: 20, image: 'assets/products/backpack.png'),
  Product(id: '10', title: 'Denim Jacket', price: 54, image: 'assets/products/jacket.png'),
];

// make a provider which can provide this data to the widgets within the application

/* replacing this with the generated code (by riverpod)
final productsProvider = Provider((ref) {
  return allProducts;
}); // provider 1 -> provides all products
*/

final reducedProducts = Provider((ref) {
  return allProducts.where((p) => p.price < 150).toList();
}); // provider 2 -> provides products which has price less than 150

// generated providers - riverpod generator which can generate provider for us
// install from terminal: flutter pub add riverpod_annotation
//                        flutter pub add dev:riverpod_generator

// for generation:flutter pub add dev:build_runner
// dart run build_runner watch

@riverpod // this annotation is used for telling that we are writing a generator code
List<Product> products(ref) {
  return allProducts; // this is provider but generated by riverpod
}

// Now provider 1 (which was providing all products is generated by riverpod)
// and provider 2 is manually written

/* If we were to make it generated by riverpod (provider 2)
@riverpod
List<Product> reducedProducts(ref){
  return allProducts.where((p) => p.price < 150).toList();
}
 */